# Generated by Django 4.2.1 on 2023-05-31 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='for_who',
        ),
        migrations.AddField(
            model_name='task',
            name='assign',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='Status',
            field=models.CharField(choices=[('1', 'Stuck'), ('2', 'Working'), ('3', 'Done')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
