# Generated by Django 4.2.1 on 2023-06-12 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0003_alter_task_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListTask',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assign',
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='authored_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
